apiVersion: v1
kind: ConfigMap
metadata:
  name: $SERVICE_NAME-environment-variables
data:
  THIS_SERVICE: $SERVICE_NAME
  BRANCH: $NAMESPACE
  domain: schulcloud-server
  TZ: Europe/Berlin
  DONT_GEN_SSL_CERT: "true"
  extra_params: --o:ssl.enable=false
